matrix:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-17
      env:
        - MATRIX_EVAL="CC=gcc-17 && CXX=g++-17"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp
compiler: gcc

script:
  - g++ --version
  - g++ main.cpp -o mybinary -std=gnu++17 - ./mybinary
